name: Health check

on:
  schedule:
    - cron:  '0 22 * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check deployed application status
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: https://fullstackopen-cicd.herokuapp.com/health
          max-attempts: 3
          retry-delay: 10s
